language: ruby
rvm:
- 2.2.0
cache: bundler
before_script:
  - bundle exec jekyll serve --detach
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4 # give jekyll some time to start
  - gem install s3_website
script: bundle exec jekyll build
after_success: s3_website push
